web:
  image: node:boron
  working_dir: /home/app
  volumes:
    - ./app:/home/app
    - ./database:/home/database
  ports:
   - 3000:8080
  links:
    - "db:database"
  command: bash -c "npm install && npm start && sh /home/database/migrate.sh"
db:
  image: mysql
  volumes:
    - ./database:/home/database
  environment:
    MYSQL_ROOT_PASSWORD: root